set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 26 [current_design]

set_property PACKAGE_PIN Y18 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
create_clock -period 20.000 -name sys_clk -waveform {0.000 10.000} [get_nets sys_clk]

set_property PACKAGE_PIN T18 [get_ports rs485_rx]
set_property IOSTANDARD LVCMOS33 [get_ports rs485_rx]
set_property PACKAGE_PIN R18 [get_ports rs485_tx]
set_property IOSTANDARD LVCMOS33 [get_ports rs485_tx]
set_property PACKAGE_PIN N17 [get_ports rs485_oe]
set_property IOSTANDARD LVCMOS33 [get_ports rs485_oe]

set_property PACKAGE_PIN V22 [get_ports dev_addr[0]]
set_property IOSTANDARD LVCMOS33 [get_ports dev_addr[0]]
set_property PACKAGE_PIN T21 [get_ports dev_addr[1]]
set_property IOSTANDARD LVCMOS33 [get_ports dev_addr[1]]
set_property PACKAGE_PIN W19 [get_ports dev_addr[2]]
set_property IOSTANDARD LVCMOS33 [get_ports dev_addr[2]]
set_property PACKAGE_PIN W20 [get_ports dev_addr[3]]
set_property IOSTANDARD LVCMOS33 [get_ports dev_addr[3]]